### ISSUE TITLE
mk-input-text not working

### ISSUE THREAD

**Issue by guicosta** [mledour/angular-admin-lte#33]
I'm trying to use input text:
`<mk-input-text name="input-name" minlength="4" maxlength="5" required placeholder="placeholder">
              <mk-input-text-label>Input label</mk-input-text-label>
            </mk-input-text>`

And getting the following error:
ERROR in : 'mk-input-text-label' is not a known element:
1. If 'mk-input-text-label' is an Angular component, then verify that it is part of this module.
2. If 'mk-input-text-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("ext name="input-name" minlength="4" maxlength="5" required placeholder="placeholder">
              [ERROR ->]<mk-input-text-label>Input label</mk-input-text-label>
            </mk-input-text>
          <button")
: 'mk-input-text' is not a known element:
1. If 'mk-input-text' is an Angular component, then verify that it is part of this module.
2. If 'mk-input-text' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
          </mk-input-group>
          <br />
          [ERROR ->]<mk-input-text name="input-name" minlength="4" maxlength="5" required placeholder="placeholder">
    ")

InputTextModule is loaded.

**Comment by mledour** [comment]
Hi,

Have you loaded the InputTextModule in the closest parent module of the component?

**Comment by guicosta** [comment]
Hi,

Yes, InputTextModule is loaded in the same module file that InputGroupModule is loaded but only <mk-input-text-label> and <mk-input-text> isn't working.
I'm using version 1.3.2.

**Comment by mledour** [comment]
This is beacause mk-input-text-label does not exists and mk-input-text is a directive

Use it like this:

```
<form [formGroup]="userForm" (ngSubmit)="onSubmitForm()">
  <mk-input-group inputErrorColor="warning">
    <mk-input-group-label>Input icons</mk-input-group-label>
    <mk-input-group-addon-left>@</mk-input-group-addon-left>
    <mk-input-group-addon-right><i [ngClass]="userForm.invalid ? 'fa fa-times' : 'fa fa-check'"></i></mk-input-group-addon-right>
    <mk-input-group-content>
      <input mkInputText formControlName="firstName" class="form-control"/>
    </mk-input-group-content>
  </mk-input-group>
  <br />
  <button type="submit" [disabled]="userForm.invalid" class="btn btn-primary">Submit</button>
</form>
```

then in the component:
```
  userForm: FormGroup;

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit() {
    this.userForm = this.formBuilder.group({
      firstName: ['', [Validators.required, Validators.email]]
    });
  }

  onSubmitForm() {
    console.log(this.userForm);
  }
```
