### ISSUE TITLE
Disable sidbare-left

### ISSUE THREAD

**Issue by eRif84** [mledour/angular-admin-lte#34]
Hi,

is there away to disable left sidbare?
I want only a menu in the header.

**Comment by mledour** [comment]
Hi,

First, remove this from your app.component.html
```
    <mk-layout-sidebar-left>
      <app-sidebar-left-inner></app-sidebar-left-inner>
    </mk-layout-sidebar-left>
````

and change this from your app.component.html 
```
<mk-layout-header logoLink="/">
```
to this: 
```
<mk-layout-header logoLink="/" [isSidebarLeftToggle]="false">
```



then add this css somewhere: 
 ```.content-wrapper { margin-left: 0 !important; }```

**Comment by eRif84** [comment]
Thx
