### ISSUE TITLE
here have problem after set 'layout':'fixed'

### ISSUE THREAD

**Issue by BulletYuan** [mledour/angular-admin-lte#39]

**Comment by BulletYuan** [comment]
it will throw a error after i setted the param in **admin-lte.conf.ts** and `ng serve`.

the message is :

```
ERROR TypeError: Cannot read property 'nativeElement' of undefined
```

find this code by develop tool in `\library\angular-admin-lte\src\lib\layout\header\header.service.ts` line 13.

```typescript
return this.elementRef.nativeElement.offsetHeight;
```

fix the error up with add a judgement at the code.

```typescript
return this.elementRef ? this.elementRef.nativeElement.offsetHeight : 0;
```

**Comment by BulletYuan** [comment]
i think the problem is the element is not created when angular rendering

**Comment by mledour** [comment]
Hi,

fixed in the latest release ;)
