### ISSUE TITLE
got an error when i used HTTP request

### ISSUE THREAD

**Issue by BulletYuan** [mledour/angular-admin-lte#40]
when i used a [http request component](https://github.com/BulletYuan/bulletHttpRequest),it will be throw an error message:

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'background-color: undefined'. Current value: 'background-color: #da4733'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
```

seems like from `ng:///MaterialBarModule/MaterialbarComponent.html` that display in my develop tool's console.

but if i remove the http request `.subscribe(void)` code,the error will remove and not errors anymore.

is that `Materialbar` dynamic created conflict with http request observable object created?

**Comment by BulletYuan** [comment]
at present, i clean the error that turn `checkPendingHttp : true` to `false` at `app.component.html` line 19.
but all http request can not display progress when pending.
have any other solutions?

**Comment by mledour** [comment]
Hi,

This project does not use material.
I think you should ask to this project directly: https://github.com/angular/components/issues
