### ISSUE TITLE
Current menu not selected

### ISSUE THREAD

**Issue by guicosta** [mledour/angular-admin-lte#42]
Hi, 

I've changed the way my custom layout works, the session layout is under the route /session in separated module, while all the other pages are under de the / route, this has cause the menu not being active anymore and only works if I set the routes this way, example:
{label: 'CLIENTS', **route: '/clients'**, iconClasses: 'fa fa-user' },
{label: 'PROJECT_LEADERS', **route: '/project-leaders'**, iconClasses: 'fa fa-trophy' }, 

If I use the config like **route: 'project-leaders'**, the link will be active in the right route but only work in the / route, in any other route, the links will be like http://localhost:4200/clients/(project-leaders)

Is there any way to make it work again?

**Comment by mledour** [comment]
Hi,

Can you fork the project, reproduce this and create a PR?
It will be deployed to https://mledour.github.io/angular-admin-lte/pulls/ID

thanks
