### ISSUE TITLE
how to add modal?

### ISSUE THREAD

**Issue by sjhds** [mledour/angular-admin-lte#45]
Is there a way to add AdminLte styles modal?

AdminLte has so many components, but angular-admin-lte seems to provide parts of them.

Does it come up with soon?

Thanks in advance.

**Comment by silverbr23** [comment]
Read, going to be worth it!

I found out how to do it! ONE GOD BLESSED DAY LOOKING FOR THAT THO  (Feel ashamed for that)

So here is the thing first you can start by taking the https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap and adding it to your project... but please check the correspondent Angular version that you are using. I tried the latest but my angular was 7.0 and it was crashing build --prod

then you can go and follow the example on site on how to add angular modal w/ bootstrap 

https://ng-bootstrap.github.io/#/components/modal/examples

ok...

After that here is the magical thing about what was causing my issue... I had added the modal to my template and it was rendering fine "according to dev tools" but it wasn't showing for me the modals... so I went to investigate why... after spending some good time I foundout that the 
"node_modules/bootstrap-css-only/css/bootstrap.min.css" guy, sets opacity to "0" on the modal stuff.

So all I had to do was go to: ../../master/src/styles.css and push some code over that bootstrap css

```
.fade {
  opacity: 1;
  transition: opacity .15s linear;
}

.modal-dialog{
  position: absolute;
  top: 40%;
  left: 40%;
  margin-right: -50%;
  transform: translate(-50%, -50%);
  width: 720px;
}
```

And that's what I did.

worked like a charm...

Cheers!

**Comment by sakkeerhussaina** [comment]
Hi,

Tried below code in ngOnInit() of AppComponent and is working fine


$(document).on('show.bs.modal', '.modal', function () {
      $(this).appendTo('body');
    });

Thanks
