### ISSUE TITLE
How to add custom menu options in side bar once Layoutmodule is loaded?

### ISSUE THREAD

**Issue by tarangpandya** [mledour/angular-admin-lte#52]
My scenario is - i can not have configured all the sidebar options from the beginning. I have to add child menus to parent once user navigate to parent child. 

How do i achieve that?

**Comment by uerlensantos** [comment]
I had a similar problem, I created a component to replace the lib menu.

<app-sidebar-left-inner></app-sidebar-left-inner>
by
<app-menu-custom></app-menu-custom>
