### ISSUE TITLE
How to set user name after login on side bar and header

### ISSUE THREAD

**Issue by sakkeerhussaina** [mledour/angular-admin-lte#53]
How to set user name after login on side bar and header. Not able to set name with subscription of event on  HeaderInnerComponent .

**Comment by mledour** [comment]
The sidebar upper section and the header section are controlled by you so you can create your own logic to show username or whatever.
HeaderInnerComponent and SidebarLeftInnerComponent are for demo and documentation to see how you can use the lib.
