### ISSUE TITLE
Error with Sidebar when it's Mini mode

### ISSUE THREAD

**Issue by iyilm4z** [mledour/angular-admin-lte#55]
When Sidebar menu is on mini mode, it shouldn't behave like in the pic below for submenus.
@CarlesLopezMagem do you have any ide bro?

![bug](https://user-images.githubusercontent.com/9105939/73164162-6ea0e680-4102-11ea-9591-d86ad75f9eb3.JPG)

**Comment by iyilm4z** [comment]
I updated admin lte to 2.4.18 which is the latest version for v2. Dropdown arrrow for the first level sub menu has gone which is expected, but it keeps 2nd level menu always open even i collapse it but it works as expected when menu is not on mini mode.

**Comment by SoftLabNS** [comment]
i changed CollapseAnimationDirective in node_modules/angular-admin-lte.js, because menu items not collapsed, only set height to 0px. 

collapse method 2218 line:

`this.renderer2.removeClass(this.elementRef.nativeElement, 'un-collapse');
                this.renderer2.setStyle(this.elementRef.nativeElement, 'display', 'none');`

**Comment by iyilm4z** [comment]
@SoftLabNS Hi, could you please show on directive's own code?
