### ISSUE TITLE
What's step for update angular 9?

### ISSUE THREAD

**Issue by jadav1982** [mledour/angular-admin-lte#56]
What's step for update angular 9?

**Comment by mledour** [comment]
angular-admin-lte has been updated for angular 9.1

**Comment by iyilm4z** [comment]
@mledour good job! Thanks for all your valuable efforts.

**Comment by deferenty** [comment]
After upgrading to Angular 9 everything works fine. But have warning during `npm install`:
`angular-admin-lte@3.0.0 requires a peer of @angular/core@^7.2.3 but none is installed. You must install peer dependencies yourself`

**Comment by mledour** [comment]
You can ignore this warnings, i forgot to update the peer dependencies of the lib. I'll fix this on the next release.
