### ISSUE TITLE
how to change icons that collapse sidebars?

### ISSUE THREAD

**Issue by dankiest** [mledour/angular-admin-lte#64]
is that possible to change this icons. I'm having a issue with the version of fontawesome. I think that it's using version 4 and i have to use version 5. There is some way to change this icons?

**Comment by PerryCodes** [comment]
Is this project abandoned?

**Comment by mledour** [comment]
Hi,
angular-admin-lte has been updated to 3.1.0.
Now you can change sidebars icon css classes.
Check the doc [here](https://mledour.github.io/angular-admin-lte/branches/master/#/layout/header)
